const RECITERS = [
  { ar: "عبد الرحمن السديس", fr: "Abdurrahman Al-Sudais" },
  { ar: "سعود الشريم", fr: "Saud Al-Shuraim" },
  { ar: "مشاري العفاسي", fr: "Mishary Al-Afasy" },
  { ar: "ماهر المعيقلي", fr: "Maher Al-Muaiqly" },
  { ar: "عبدالباسط عبدالصمد", fr: "Abdel Baset Abdel Samad" },
  { ar: "محمد صديق المنشاوي", fr: "Mohamed Siddiq El-Minshawi" },
  { ar: "فارس عباد", fr: "Fares Abbad" },
  { ar: "ياسر الدوسري", fr: "Yasser Al-Dosari" },
  { ar: "خالد عبدالكافي", fr: "Khaled Abdel-Kafi" },
  { ar: "إدريس أبكر", fr: "Idriss Abkar" },
  { ar: "علي الحذيفي", fr: "Ali Al-Hudhaifi" },
  { ar: "هاني الرفاعي", fr: "Hani Al-Rifai" },
  { ar: "أحمد العجمي", fr: "Ahmed Al-Ajmi" },
  { ar: "وديع اليمني", fr: "Wadi Al-Yamani" },
  { ar: "سيد رمضان", fr: "Sayed Ramadan" },
  { ar: "توفيق الصايغ", fr: "Tawfiq Al-Sayegh" },
  { ar: "محمد اللحيدان", fr: "Muhammad Al-Luhaidan" },
  { ar: "نبيل الرفاعي", fr: "Nabil Al-Rifai" },
  { ar: "عبدالله الجهني", fr: "Abdullah Al-Juhani" },
  { ar: "صالح آل طالب", fr: "Salah Al Talib" },
];

const SURAHS = [
  { n: 1,   ar: "الفاتحة",     fr: "Al-Fatiha",      v: 7   },
  { n: 2,   ar: "البقرة",      fr: "Al-Baqara",      v: 286 },
  { n: 3,   ar: "آل عمران",    fr: "Al-Imran",       v: 200 },
  { n: 4,   ar: "النساء",      fr: "An-Nisa",        v: 176 },
  { n: 5,   ar: "المائدة",     fr: "Al-Ma'ida",      v: 120 },
  { n: 6,   ar: "الأنعام",     fr: "Al-An'am",       v: 165 },
  { n: 7,   ar: "الأعراف",     fr: "Al-A'raf",       v: 206 },
  { n: 8,   ar: "الأنفال",     fr: "Al-Anfal",       v: 75  },
  { n: 9,   ar: "التوبة",      fr: "At-Tawba",       v: 129 },
  { n: 10,  ar: "يونس",        fr: "Yunus",          v: 109 },
  { n: 11,  ar: "هود",         fr: "Hud",            v: 123 },
  { n: 12,  ar: "يوسف",        fr: "Yusuf",          v: 111 },
  { n: 13,  ar: "الرعد",       fr: "Ar-Ra'd",        v: 43  },
  { n: 14,  ar: "إبراهيم",     fr: "Ibrahim",        v: 52  },
  { n: 15,  ar: "الحجر",       fr: "Al-Hijr",        v: 99  },
  { n: 16,  ar: "النحل",       fr: "An-Nahl",        v: 128 },
  { n: 17,  ar: "الإسراء",     fr: "Al-Isra",        v: 111 },
  { n: 18,  ar: "الكهف",       fr: "Al-Kahf",        v: 110 },
  { n: 19,  ar: "مريم",        fr: "Maryam",         v: 98  },
  { n: 20,  ar: "طه",          fr: "Ta-Ha",          v: 135 },
  { n: 21,  ar: "الأنبياء",    fr: "Al-Anbiya",      v: 112 },
  { n: 22,  ar: "الحج",        fr: "Al-Hajj",        v: 78  },
  { n: 23,  ar: "المؤمنون",    fr: "Al-Mu'minun",    v: 118 },
  { n: 24,  ar: "النور",       fr: "An-Nur",         v: 64  },
  { n: 25,  ar: "الفرقان",     fr: "Al-Furqan",      v: 77  },
  { n: 26,  ar: "الشعراء",     fr: "Ash-Shu'ara",    v: 227 },
  { n: 27,  ar: "النمل",       fr: "An-Naml",        v: 93  },
  { n: 28,  ar: "القصص",       fr: "Al-Qasas",       v: 88  },
  { n: 29,  ar: "العنكبوت",    fr: "Al-Ankabut",     v: 69  },
  { n: 30,  ar: "الروم",       fr: "Ar-Rum",         v: 60  },
  { n: 31,  ar: "لقمان",       fr: "Luqman",         v: 34  },
  { n: 32,  ar: "السجدة",      fr: "As-Sajda",       v: 30  },
  { n: 33,  ar: "الأحزاب",     fr: "Al-Ahzab",       v: 73  },
  { n: 34,  ar: "سبأ",         fr: "Saba",           v: 54  },
  { n: 35,  ar: "فاطر",        fr: "Fatir",          v: 45  },
  { n: 36,  ar: "يس",          fr: "Ya-Sin",         v: 83  },
  { n: 37,  ar: "الصافات",     fr: "As-Saffat",      v: 182 },
  { n: 38,  ar: "ص",           fr: "Sad",            v: 88  },
  { n: 39,  ar: "الزمر",       fr: "Az-Zumar",       v: 75  },
  { n: 40,  ar: "غافر",        fr: "Ghafir",         v: 85  },
  { n: 41,  ar: "فصلت",        fr: "Fussilat",       v: 54  },
  { n: 42,  ar: "الشورى",      fr: "Ash-Shura",      v: 53  },
  { n: 43,  ar: "الزخرف",      fr: "Az-Zukhruf",     v: 89  },
  { n: 44,  ar: "الدخان",      fr: "Ad-Dukhan",      v: 59  },
  { n: 45,  ar: "الجاثية",     fr: "Al-Jathiya",     v: 37  },
  { n: 46,  ar: "الأحقاف",     fr: "Al-Ahqaf",       v: 35  },
  { n: 47,  ar: "محمد",        fr: "Muhammad",       v: 38  },
  { n: 48,  ar: "الفتح",       fr: "Al-Fath",        v: 29  },
  { n: 49,  ar: "الحجرات",     fr: "Al-Hujurat",     v: 18  },
  { n: 50,  ar: "ق",           fr: "Qaf",            v: 45  },
  { n: 51,  ar: "الذاريات",    fr: "Adh-Dhariyat",   v: 60  },
  { n: 52,  ar: "الطور",       fr: "At-Tur",         v: 49  },
  { n: 53,  ar: "النجم",       fr: "An-Najm",        v: 62  },
  { n: 54,  ar: "القمر",       fr: "Al-Qamar",       v: 55  },
  { n: 55,  ar: "الرحمن",      fr: "Ar-Rahman",      v: 78  },
  { n: 56,  ar: "الواقعة",     fr: "Al-Waqi'a",      v: 96  },
  { n: 57,  ar: "الحديد",      fr: "Al-Hadid",       v: 29  },
  { n: 58,  ar: "المجادلة",    fr: "Al-Mujadila",    v: 22  },
  { n: 59,  ar: "الحشر",       fr: "Al-Hashr",       v: 24  },
  { n: 60,  ar: "الممتحنة",    fr: "Al-Mumtahana",   v: 13  },
  { n: 61,  ar: "الصف",        fr: "As-Saf",         v: 14  },
  { n: 62,  ar: "الجمعة",      fr: "Al-Jumu'a",      v: 11  },
  { n: 63,  ar: "المنافقون",   fr: "Al-Munafiqun",   v: 11  },
  { n: 64,  ar: "التغابن",     fr: "At-Taghabun",    v: 18  },
  { n: 65,  ar: "الطلاق",      fr: "At-Talaq",       v: 12  },
  { n: 66,  ar: "التحريم",     fr: "At-Tahrim",      v: 12  },
  { n: 67,  ar: "الملك",       fr: "Al-Mulk",        v: 30  },
  { n: 68,  ar: "القلم",       fr: "Al-Qalam",       v: 52  },
  { n: 69,  ar: "الحاقة",      fr: "Al-Haqqah",      v: 52  },
  { n: 70,  ar: "المعارج",     fr: "Al-Ma'arij",     v: 44  },
  { n: 71,  ar: "نوح",         fr: "Nuh",            v: 28  },
  { n: 72,  ar: "الجن",        fr: "Al-Jinn",        v: 28  },
  { n: 73,  ar: "المزمل",      fr: "Al-Muzzammil",   v: 20  },
  { n: 74,  ar: "المدثر",      fr: "Al-Muddaththir", v: 56  },
  { n: 75,  ar: "القيامة",     fr: "Al-Qiyama",      v: 40  },
  { n: 76,  ar: "الإنسان",     fr: "Al-Insan",       v: 31  },
  { n: 77,  ar: "المرسلات",    fr: "Al-Mursalat",    v: 50  },
  { n: 78,  ar: "النبأ",       fr: "An-Naba",        v: 40  },
  { n: 79,  ar: "النازعات",    fr: "An-Nazi'at",     v: 46  },
  { n: 80,  ar: "عبس",         fr: "'Abasa",         v: 42  },
  { n: 81,  ar: "التكوير",     fr: "At-Takwir",      v: 29  },
  { n: 82,  ar: "الانفطار",    fr: "Al-Infitar",     v: 19  },
  { n: 83,  ar: "المطففين",    fr: "Al-Mutaffifin",  v: 36  },
  { n: 84,  ar: "الانشقاق",    fr: "Al-Inshiqaq",    v: 25  },
  { n: 85,  ar: "البروج",      fr: "Al-Buruj",       v: 22  },
  { n: 86,  ar: "الطارق",      fr: "At-Tariq",       v: 17  },
  { n: 87,  ar: "الأعلى",      fr: "Al-A'la",        v: 19  },
  { n: 88,  ar: "الغاشية",     fr: "Al-Ghashiya",    v: 26  },
  { n: 89,  ar: "الفجر",       fr: "Al-Fajr",        v: 30  },
  { n: 90,  ar: "البلد",       fr: "Al-Balad",       v: 20  },
  { n: 91,  ar: "الشمس",       fr: "Ash-Shams",      v: 15  },
  { n: 92,  ar: "الليل",       fr: "Al-Layl",        v: 21  },
  { n: 93,  ar: "الضحى",       fr: "Ad-Duha",        v: 11  },
  { n: 94,  ar: "الشرح",       fr: "Ash-Sharh",      v: 8   },
  { n: 95,  ar: "التين",       fr: "At-Tin",         v: 8   },
  { n: 96,  ar: "العلق",       fr: "Al-'Alaq",       v: 19  },
  { n: 97,  ar: "القدر",       fr: "Al-Qadr",        v: 5   },
  { n: 98,  ar: "البينة",      fr: "Al-Bayyina",     v: 8   },
  { n: 99,  ar: "الزلزلة",     fr: "Az-Zalzala",     v: 8   },
  { n: 100, ar: "العاديات",    fr: "Al-'Adiyat",     v: 11  },
  { n: 101, ar: "القارعة",     fr: "Al-Qari'a",      v: 11  },
  { n: 102, ar: "التكاثر",     fr: "At-Takathur",    v: 8   },
  { n: 103, ar: "العصر",       fr: "Al-'Asr",        v: 3   },
  { n: 104, ar: "الهمزة",      fr: "Al-Humaza",      v: 9   },
  { n: 105, ar: "الفيل",       fr: "Al-Fil",         v: 5   },
  { n: 106, ar: "قريش",        fr: "Quraysh",        v: 4   },
  { n: 107, ar: "الماعون",     fr: "Al-Ma'un",       v: 7   },
  { n: 108, ar: "الكوثر",      fr: "Al-Kawthar",     v: 3   },
  { n: 109, ar: "الكافرون",    fr: "Al-Kafirun",     v: 6   },
  { n: 110, ar: "النصر",       fr: "An-Nasr",        v: 3   },
  { n: 111, ar: "المسد",       fr: "Al-Masad",       v: 5   },
  { n: 112, ar: "الإخلاص",     fr: "Al-Ikhlas",      v: 4   },
  { n: 113, ar: "الفلق",       fr: "Al-Falaq",       v: 5   },
  { n: 114, ar: "الناس",       fr: "An-Nas",         v: 6   },
];

const VERSE_TEXTS = {
  1: [
    "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ",
    "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ",
    "الرَّحْمَنِ الرَّحِيمِ",
    "مَالِكِ يَوْمِ الدِّينِ",
    "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ",
    "اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ",
    "صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ",
  ],
  112: [
    "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ هُوَ اللَّهُ أَحَدٌ",
    "اللَّهُ الصَّمَدُ",
    "لَمْ يَلِدْ وَلَمْ يُولَدْ",
    "وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ",
  ],
  113: [
    "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ",
    "مِنْ شَرِّ مَا خَلَقَ",
    "وَمِنْ شَرِّ غَاسِقٍ إِذَا وَقَبَ",
    "وَمِنْ شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ",
    "وَمِنْ شَرِّ حَاسِدٍ إِذَا حَسَدَ",
  ],
  114: [
    "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ قُلْ أَعُوذُ بِرَبِّ النَّاسِ",
    "مَلِكِ النَّاسِ",
    "إِلَهِ النَّاسِ",
    "مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ",
    "الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ",
    "مِنَ الْجِنَّةِ وَالنَّاسِ",
  ],
};
